name: Wisp
options:
  bundleIdPrefix: com.wisp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
settings:
  SWIFT_VERSION: "6.0"
  SWIFT_STRICT_CONCURRENCY: complete
packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"
targets:
  Wisp:
    type: application
    platform: iOS
    sources:
      - Wisp
    settings:
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      GENERATE_INFOPLIST_FILE: true
      PRODUCT_BUNDLE_IDENTIFIER: com.wisp.app
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      INFOPLIST_KEY_CFBundleDisplayName: Wisp
    dependencies:
      - package: MarkdownUI
